version: '3.8'

services:

  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  postgres_test:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5532:5432
    volumes:
      - dev-db-test-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
  dev-db-test-data: